matrix:
  fast_finish: true
env:
  matrix:
  - COZY_APP_SLUG=drive
  - COZY_APP_SLUG=photos
  global:
  - REGISTRY_EDITOR=Cozy
  - secure: jkeLwtuN/GRKtDn8UK9O4rXQtptfD6QhAM3TgxbGseu2gxWhE/BKs/XndQgz1ty+ZzYIxoBeEbbfSges7aENz/DejYiZ4HJpwVnlGXta9+YsyyH96uj8JKU/T4qCjbcK09YjG/OCElUQ/inst4nRN9r52kCYWJnnTz7ilxcyvB/Qfjp7XrtsEakRYN5tq5HMnd3QCzdXQI48b0+Nl/B0p/nRYVZaUOxuom2kFXCKmvmNkJ2AnQ80aVNSrAjU8jnoIdt7r5rJF0PnIRkEdHTmSKB7uOokW9MIDizTWZN0dCHpgI9vtHXLopLctD9jrS+pSpmkTtBxtn9hQ+OR9qxrY0ZtWC6I92ztAGVahwP6WgjZ0Qm5jJ7BaCkeMxVTjRpcyu6NqGiFGuUyUYMlAqRrQPNmArjt/8EAQbCCPamsZ0kLgkBEtTHMRdDd8+u45zL6u8Sq4Ab601AN65rb/KiGid81ObGPBug+ihgZOb5q3QQ+LCElJKwgU+9vzUx2eY07SMZaREg4ouib1a5qim2K+K6d2gN5eBpOdq9HcGsT53CUHRu9s4fefEAOXENoUIgg6EBgaJRLwhSzhX5bgpu8Kn0VbIq7fiaoG72SFC/FL+fRli7VOeAReRoYpNfY1n1REXRtBIdtoiUlzlBBLUFwM20mZehs08//5jISPIvrWjc=
script:
- sh publish_registry.sh
